### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by nimmen** [BraveSirRobin/amqphp#3]
Hello, Im having some issues trying to connect to rabbitmq on freebsd
client side error(after enabled the debug):

<write>

<read>
00000000
Fatal error: Uncaught exception 'Exception' with message 'Connection initialisation failed (2)' in C:...\BraveSirRobin-amqphp-9e465b9
\amqphp\Connection.php on line 184

Exception: Connection initialisation failed (2) in C:...\BraveSirRobin-amqphp-9e465b9\amqphp\Connection.php on line 184

server side info:
=INFO REPORT==== 28-Apr-2011::16:10:38 ===
accepted TCP connection on 0.0.0.0:5672 from ...:60320

=INFO REPORT==== 28-Apr-2011::16:10:38 ===
starting TCP connection <0.22516.0> from ...:60320

=ERROR REPORT==== 28-Apr-2011::16:10:48 ===
exception on TCP connection <0.22516.0> from ...:60320
{handshake_timeout,frame_header}

=INFO REPORT==== 28-Apr-2011::16:10:48 ===
closing TCP connection <0.22516.0> from ...:60320

Im using php 5.3.6 on client (windows)
rabbitmq-2.3.1 on freebsd 8.2 stable
i use user with password and vhost(who i pass to Connection constructor), im sure that user does exist and has password set and all permissions are right on that vhost, but it seems client never goes up to auth stage.

**Comment by BraveSirRobin** [comment]
Hi Nimmen,

Are you running the very latest version of Amqphp?

--Robin

**Comment by nimmen** [comment]
I did try both branches(that is in last 7-10 days timeframe, last change i see is on April 09, 2011).
I think they are latest, but problem was same on both branches.
Also i did try other php amqp extension from bkw, it did work, so im quite sure its not server side problem.
I did find this because i had in mind porting rabbitmq/amqp client from java to php, because there seems to be a lack of decent one for php, so far Your project seems very interesting and im interested in helping(rather than creating port of java client, which would take quite some time).

**Comment by BraveSirRobin** [comment]
Hi Nimmen,

It's most likely a problem with the handshake process - this changed recently due to issues with Rabbit 2.4.0.  I'll downgrade my Rabbit over the weekend and see if I can reproduce the error.

I'd be delighted to have some more contributers, do you have anything in mind that you'd like to contribute?  If you like I could put a wish list up on the Wiki and list some jobs that interested parties could do.

Thanks,
--Robin

**Comment by nimmen** [comment]
Right now i was interested in just making it work, so i could be sure that its worth spending my free time helping You (if You needed any help), or forking it (dont see what, if any, license is this project under).
At first i would like to check the structure of code/files/namespaces more deeply, cleanup, offer, discuss some decisions You use.

**Comment by BraveSirRobin** [comment]
Okay, that's fine.  I'll investigate this error over the weekend and get back to you on what I find.  BTW, the code is LGPL 2.1, there's a bunch of legal mumbo jumbo at the top of each file in a comment.  IANAL ;-)

**Comment by BraveSirRobin** [comment]
Hi Nimmen

I've just quickly downgraded to 2.3.1 (Linux, Ubuntu, 64 bit) and the demo-consumer.php and demo-producer.php scripts both work fine for me.  Looking more closely at your report, I think this might be a platform issue - unfortunately I don't have a copy of Windows to test on.  (Come to think of it, here's a good way you could help out with Amqphp ;-)

The PHP exception message you listed above is thrown at the very top of the  Amqp protocol handshake sequence, all that's happened up till that point is that you've opened up a TCP connection and written "AMQP 0.9.1" to it; this is well _before_ the RabbitMQ 2.4.0 fix I mentioned earlier happened.

The most obvious suggestion I have is to try the other socket handler, if you set `['socketImpl'] => '\amqp_091\StreamSocket'` somewhere in the `amqp\Connection` constructor parameters that will switch you over to using the PHP stream extension rather than the socket extension, i.e. http://www.php.net/manual/en/book.stream.php instead of http://www.php.net/manual/en/ref.sockets.php

As I said, I don't have a copy of Windows, so I'd be very grateful if you could spend a bit of time investigating.

Many Thanks,
--Robin

**Comment by nimmen** [comment]
Thanks for the tips, i dont know much about sockets in php, just know that we did have some problems with rabbitmq and client on windows with half open ports(but that was with some old library of amqp for php, i dont really remember how solved this issue), but it definitely went past handshake, i think issues happened with consumers on windows.
Ill try what You suggested.
Cheers

**Comment by nimmen** [comment]
streamsocket implementation seems to work,
but there are some things like
'Call to undefined function amqphp\pcntl_signal_dispatch()' which is another issue, platform specific.
Also few minor things as passing url to connection constructor didnt seem to work and etc...
Which branch would be better for me to work on?
